common: &common
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: SQL_ASCII
  template: template0
  pool: 5
  timeout: 5000

local: &local
  host: 127.0.0.1

# -----------------
# *** part ***
# -----------------

development:
  <<: *common
  <<: *local
  database:bulk_data_methods_development

production:
  <<: *common
  <<: *local
  database: bulk_data_methods_production


test:
  <<: *common
  <<: *local
  database: bulk_data_methods_test